#!/bin/sh

set -e

fixperms() {
    chown -R www-data:adm \
        /var/cache/chwala \
        /var/lib/chwala \
        /var/log/chwala
    chmod 750 \
        /var/cache/chwala \
        /var/lib/chwala \
        /var/log/chwala
}

reload_apache()
{
    if apache2ctl configtest 2>/dev/null; then
        invoke-rc.d apache2 $1 || true
    else
        echo "Your apache2 configuration is broken, so we're not restarting it for you."
    fi
}


case "$1" in
    configure)
        fixperms
        a2enmod rewrite >/dev/null 2>&1 || true
        if [ -e "/etc/apache2/sites-available/chwala" -a ! -e "/etc/apache2/sites-enabled/chwala" ]; then
            a2ensite chwala
        fi
        reload_apache reload
    ;;
esac

exit 0
